FROM node:14-alpine as builder

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile --no-cache

# note: eslintrc must be copied
# https://github.com/facebook/create-react-app/issues/9791
COPY tsconfig.json webpack.config.server.ts .eslintrc.js ./
COPY public/ ./public
COPY src/ ./src

ENV NODE_ENV production
ENV WEBPACK_NODE_MODULES true
RUN yarn build:server
RUN mv -v build/ server/

# https://create-react-app.dev/docs/adding-custom-environment-variables/
# ARG PROTOCOL=http
# ENV REACT_APP_BACKEND_PROTOCOL $PROTOCOL

RUN yarn build:client
RUN mv -v build/ client/

RUN yarn build:plugin
RUN mv -v build/ plugin/

COPY README.md ./

##################################################

FROM node:14-alpine

# ARG BUILD_DATE
ARG VCS_REF

LABEL org.label-schema.schema-version="1.0"
# LABEL org.label-schema.build-date=$BUILD_DATE
LABEL org.label-schema.name="redhat-actions/openshift-actions-connector"
LABEL org.label-schema.url="https://github.com/redhat-actions/openshift-actions-connector"
LABEL org.label-schema.vsc-ref=$VSC_REF

# ARG USER=node
ARG USER=1000
ENV USER $USER

RUN mkdir -v /app  \
    && chown $USER:0 /app \
    && chmod 774 /app
WORKDIR /app

RUN apk add curl

COPY --chown=$USER package.json yarn.lock ./
RUN yarn global add --frozen-lockfile \
    # This package is used to serve the bundled, static react app
    serve
    # These are the external dependencies
    # as specified in server webpack.config
    # log4js express @kubernetes/client-node

USER $USER

ENV NODE_ENV production

ARG FRONTEND_PORT=3000
# ENV FRONTEND_PROTOCOL $PROTOCOL
ENV FRONTEND_PORT $FRONTEND_PORT

ARG PLUGIN_PORT=3001
ENV PLUGIN_PORT $PLUGIN_PORT

ARG BACKEND_PORT=3003
ENV BACKEND_PORT $BACKEND_PORT

EXPOSE $FRONTEND_PORT
EXPOSE $PLUGIN_PORT
EXPOSE $BACKEND_PORT

COPY --chown=$USER containerize/entrypoint.sh ./
COPY --chown=$USER --from=builder /app/client ./client
COPY --chown=$USER --from=builder /app/plugin ./plugin
COPY --chown=$USER --from=builder /app/server ./server

ENTRYPOINT "./entrypoint.sh"
